version: '2'

services:
    zookeeper2:
        extends:
            file: kafka-zookeeper-base.yaml
            service: zookeeper-base
        container_name: zookeeper2
        hostname: zookeeper2
        environment:
            - ZOO_MY_ID=3
            - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2988:3988 server.3=zookeeper2:2888:3888
        extra_hosts:
            - "zookeeper0:10.0.0.7"
            - "zookeeper1:10.0.0.7"
            - "kafka0:10.0.0.7"
            - "kafka1:10.0.0.7"
        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"