version: '2'

services:
    zookeeper-base:
        image: hyperledger/fabric-zookeeper:latest
        expose:
            - '2181'
            - '2888'
            - '3888'
    
    kafka-base:
        image: hyperledger/fabric-kafka:latest
        environment:
            - KAFKA_MESSAGE_MAX_BYTES=103809024
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
            - KAFKA_UNCLEAN_LEADER_ELECTION=false
        expose:
            - '9092'