Capabilities:
        Global: &ChannelCapabilities
          V1_3: true
          V1_1: true
        Orderer: &OrdererCapabilites
          V1_1: true
        Application: &ApplicationCapabilites
          V1_3: true
          V1_2: true
          V1_1: true

Organizations:
        - &copyrightAssociateOrg
                Name: copyrightAssociateOrgMSP
                ID: copyrightAssociateOrgMSP
                MSPDir: crypto-config/peerOrganizations/copyrightOrg/msp
                AnchorPeers:
                        - Host: 10.0.0.3 
                          Port: 7051
                Policies: &copyrightAssociateOrgPolicies
                        Readers:
                                Type: Signature
                                Rule: "OR('copyrightAssociateOrgMSP.member','digitalAuthorOrgMSP.member')"
                        Writers:
                                Type: Signature
                                Rule: "OR('copyrightAssociateOrgMSP.member','digitalAuthorOrgMSP.member')"
                        Admins:
                                Type: Signature
                                Rule: "OR('copyrightAssociateOrgMSP.admin','digitalAuthorOrgMSP.admin')"
        - &digitalAuthorOrg
                Name: digitalAuthorOrgMSP
                ID: digitalAuthorOrgMSP
                MSPDir: crypto-config/peerOrganizations/digitalAuthorOrg/msp
                AnchorPeers:
                        - Host: 10.0.0.4
                          Port: 7051
                Policies: &digitalAuthorOrgPolicies
                        Readers:
                                Type: Signature
                                Rule: "OR('copyrightAssociateOrgMSP.member','digitalAuthorOrgMSP.member')"
                        Writers:
                                Type: Signature
                                Rule: "OR('copyrightAssociateOrgMSP.member','digitalAuthorOrgMSP.member')"
                        Admins:
                                Type: Signature
                                Rule: "OR('copyrightAssociateOrgMSP.admin','digitalAuthorOrgMSP.admin')"

Orderer: &OrdererDefaults
        OrdererType: kafka
        Addresses:
                - 10.0.0.3:7050
                - 10.0.0.4:7050
        Policies:
                Readers:
                        Type: ImplicitMeta
                        Rule: "ANY Readers"
                Writers:
                        Type: ImplicitMeta
                        Rule: "ANY Writers"
                Admins:
                        Type: ImplicitMeta
                        Rule: "MAJORITY Admins"
        BatchTimeout: 1s
        BatchSize:
                MaxMessageCount: 30
                AbsoluteMaxBytes: 99 MB
                PreferredMaxBytes: 512 KB
        kafka:
                Brokers:
                        - 10.0.0.7:9092
                        - 10.0.0.7:10092
                        - 10.0.0.8:9092
                        - 10.0.0.8:10092
        Capabilities:
                <<: *OrdererCapabilites
        Organizations:

Channel: &ChannelDefaults
        Policies:
                Readers:
                        Type: ImplicitMeta
                        Rule: "ANY Readers"
                Writers:
                        Type: ImplicitMeta
                        Rule: "ANY Writers"
                Admins:
                        Type: ImplicitMeta
                        Rule: "MAJORITY Admins"
        Capabilities:
                <<: *ChannelCapabilities

Application: &ApplicationDefaults
        Policies:
                Readers:
                        Type: ImplicitMeta
                        Rule: "ANY Readers"
                Writers:
                        Type: ImplicitMeta
                        Rule: "ANY Writers"
                Admins:
                        Type: ImplicitMeta
                        Rule: "MAJORITY Admins"
        Organizations:

Profiles:
        AuctionOrdererGenesis:
                Capabilities:
                        <<: *ChannelCapabilities
                <<: *ChannelDefaults
                Orderer:
                        <<: *OrdererDefaults
                        Organizations:
                                - *copyrightAssociateOrg
                                - *digitalAuthorOrg
                Consortiums:
                        AuctionConsortium:
                                Organizations:
                                        - *copyrightAssociateOrg
                                        - *digitalAuthorOrg
        AuctionChannel:
                Capabilities:
                        <<: *ChannelCapabilities
                <<: *ChannelDefaults
                Consortium: AuctionConsortium
                Application:
                        <<: *ApplicationDefaults
                        Organizations:
                                - *copyrightAssociateOrg
                                - *digitalAuthorOrg
                        Capabilities:
                                <<: *ApplicationCapabilites
